"""init schema

Revision ID: 299ebf3643bd
Revises: 
Create Date: 2026-09-07 11:47:53.229171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299ebf3643bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_name_overrides',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employment_number', sa.String(), nullable=False),
    sa.Column('bricks_display_name', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employment_number')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zenhr_employee_id', sa.Integer(), nullable=False),
    sa.Column('employment_number', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('onboarding_status', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('hiring_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('off_weekdays', sa.JSON(), nullable=False),
    sa.Column('bricks_user_id', sa.String(), nullable=True),
    sa.Column('bricks_display_name', sa.String(), nullable=True),
    sa.Column('vacation_balance_days', sa.Float(), nullable=True),
    sa.Column('vacation_balance_override_days', sa.Float(), nullable=True),
    sa.Column('vacation_balance_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_zenhr_employee_id'), 'employees', ['zenhr_employee_id'], unique=True)
    op.create_table('holidays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('job_role_category_rules',
    sa.Column('job_role', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('job_role')
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('zenhr_oauth_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_records_attendance_date'), 'attendance_records', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_table('leave_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('zenhr_transaction_id', sa.String(), nullable=True),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zenhr_transaction_id')
    )
    op.create_index(op.f('ix_leave_transactions_employee_id'), 'leave_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_transactions_leave_date'), 'leave_transactions', ['leave_date'], unique=False)
    op.create_table('vacation_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('zenhr_transaction_id', sa.String(), nullable=True),
    sa.Column('vacation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('vacation_type', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zenhr_transaction_id')
    )
    op.create_index(op.f('ix_vacation_transactions_employee_id'), 'vacation_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_vacation_transactions_vacation_date'), 'vacation_transactions', ['vacation_date'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bricks_visit_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('owner_bricks_id', sa.String(), nullable=False),
    sa.Column('owner_name_raw', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('visit_time', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bricks_visit_id')
    )
    op.create_index(op.f('ix_visits_employee_id'), 'visits', ['employee_id'], unique=False)
    op.create_index(op.f('ix_visits_owner_bricks_id'), 'visits', ['owner_bricks_id'], unique=False)
    op.create_index(op.f('ix_visits_visit_time'), 'visits', ['visit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_time'), table_name='visits')
    op.drop_index(op.f('ix_visits_owner_bricks_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_employee_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_vacation_transactions_vacation_date'), table_name='vacation_transactions')
    op.drop_index(op.f('ix_vacation_transactions_employee_id'), table_name='vacation_transactions')
    op.drop_table('vacation_transactions')
    op.drop_index(op.f('ix_leave_transactions_leave_date'), table_name='leave_transactions')
    op.drop_index(op.f('ix_leave_transactions_employee_id'), table_name='leave_transactions')
    op.drop_table('leave_transactions')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_attendance_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('zenhr_oauth_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sync_runs')
    op.drop_table('job_role_category_rules')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_employees_zenhr_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('employee_name_overrides')
    # ### end Alembic commands ###
