"""add department category rules, employee manager fields

Revision ID: 3cbb4bcdf7c5
Revises: 299ebf3643bd
Create Date: 2026-09-07 13:38:48.174091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbb4bcdf7c5'
down_revision = '299ebf3643bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_category_rules',
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('department')
    )
    op.add_column('employees', sa.Column('manager_name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('manager_zenhr_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'manager_zenhr_id')
    op.drop_column('employees', 'manager_name')
    op.drop_table('department_category_rules')
    # ### end Alembic commands ###
