"""unify timeoff model, drop vacation balance sync, add branch id

Revision ID: f199520fd199
Revises: 3cbb4bcdf7c5
Create Date: 2026-09-07 14:12:59.705901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f199520fd199'
down_revision = '3cbb4bcdf7c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeoff_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('is_sick_vacation', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeoff_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('zenhr_transaction_id', sa.Integer(), nullable=False),
    sa.Column('timeoff_type_id', sa.Integer(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['timeoff_type_id'], ['timeoff_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zenhr_transaction_id')
    )
    op.create_index(op.f('ix_timeoff_transactions_employee_id'), 'timeoff_transactions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_timeoff_transactions_from_date'), 'timeoff_transactions', ['from_date'], unique=False)
    op.drop_index('ix_leave_transactions_employee_id', table_name='leave_transactions')
    op.drop_index('ix_leave_transactions_leave_date', table_name='leave_transactions')
    op.drop_table('leave_transactions')
    op.drop_index('ix_vacation_transactions_employee_id', table_name='vacation_transactions')
    op.drop_index('ix_vacation_transactions_vacation_date', table_name='vacation_transactions')
    op.drop_table('vacation_transactions')
    op.add_column('employees', sa.Column('zenhr_branch_id', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_employees_zenhr_branch_id'), 'employees', ['zenhr_branch_id'], unique=False)
    op.drop_column('employees', 'vacation_balance_synced_at')
    op.drop_column('employees', 'vacation_balance_override_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('vacation_balance_override_days', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('vacation_balance_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_zenhr_branch_id'), table_name='employees')
    op.drop_column('employees', 'zenhr_branch_id')
    op.create_table('vacation_transactions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zenhr_transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('vacation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vacation_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='vacation_transactions_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vacation_transactions_pkey'),
    sa.UniqueConstraint('zenhr_transaction_id', name='vacation_transactions_zenhr_transaction_id_key')
    )
    op.create_index('ix_vacation_transactions_vacation_date', 'vacation_transactions', ['vacation_date'], unique=False)
    op.create_index('ix_vacation_transactions_employee_id', 'vacation_transactions', ['employee_id'], unique=False)
    op.create_table('leave_transactions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zenhr_transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('leave_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('leave_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='leave_transactions_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='leave_transactions_pkey'),
    sa.UniqueConstraint('zenhr_transaction_id', name='leave_transactions_zenhr_transaction_id_key')
    )
    op.create_index('ix_leave_transactions_leave_date', 'leave_transactions', ['leave_date'], unique=False)
    op.create_index('ix_leave_transactions_employee_id', 'leave_transactions', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_timeoff_transactions_from_date'), table_name='timeoff_transactions')
    op.drop_index(op.f('ix_timeoff_transactions_employee_id'), table_name='timeoff_transactions')
    op.drop_table('timeoff_transactions')
    op.drop_table('timeoff_types')
    # ### end Alembic commands ###
